name: 'NPM Lock Changes'
description: 'Creates a comment inside Pull Request with the human-readable summary of the changes to the "package-lock.json" file.'
branding:
  icon: 'copy'
  color: 'yellow'
inputs:
  collapsibleThreshold:
    description: 'Number of lock changes, which will result in collapsed comment content, and an addition of changes summary table.'
    required: false
    default: '25'
  failOnDowngrade:
    description: 'Fail the action when a dependency downgrade is detected. Comment will still be posted.'
    required: false
    default: 'false'
  path:
    description: 'Path to the "package-lock.json" file in the repository. Default value points to the file at project root.'
    required: false
    default: 'package-lock.json'
  token:
    description: 'GitHub token for the bot, so it can publish a comment in the pull request.'
    required: true
  updateComment:
    description: 'Update the comment on each new commit. If value is set to "false", bot will post a new one on each change.'
    required: false
    default: 'true'
  groupByType:
    description: 'Group the dependencies in the comment table by the change type.'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
